### ISSUE TITLE
关于item和actor的问题

### ISSUE THREAD

**Issue by mozhiyun** [kercylan98/minotaur#57]
请教下大佬game目录下的actor和item的区别

**Comment by kercylan98** [comment]
Actor 和 Item 都是早期设计的接口，Actor 用于之前的 World 结构，但是 World 似乎没有什么意义，后来已经去除。目前 Actor 仅被 aoi 包使用。而 Item 是用于背包成员的接口，目前不建议使用。

在后面的考虑中，game 目录下会逐步移除单个 .go 文件，游戏相关的内容会单独抽离到 game 下的子目录中。

之前提到的 World 为什么会觉得没有什么意义呢，主要是大世界的管理不是这么简单能实现概括的。所以移除了这个设计，像相对小的空间管理，例如房间，则可以通过 space 包进行使用。后续如果有 World 的实现也将会在 space 包进行更新。

**Comment by mozhiyun** [comment]
谢谢大佬解答，最近想学习下游戏开发，找了很多golang的框架，感觉你这个最有前途，准备仔细学习一下

**Comment by kercylan98** [comment]
目前来说文档测试各方面可能不太完善，变动也可能会较大。如果有什么建议，欢迎随时提出。感谢支持！
