### ISSUE TITLE
README 上 websocket 例子 需要修改

### ISSUE THREAD

**Issue by kuchaguangjie** [kercylan98/minotaur#65]
README 上 websocket 例子 应该改成:
>	srv.RegConnectionReceivePacketEvent(func(srv *server.Server, conn *server.Conn, packet []byte) {

**Comment by kercylan98** [comment]
> README 上 websocket 例子 应该改成:
> 
> > srv.RegConnectionReceivePacketEvent(func(srv *server.Server, conn *server.Conn, packet []byte) {

感谢审阅并指出！
