### ISSUE TITLE
关于新版复杂任务的配置问题

### ISSUE THREAD

**Issue by mozhiyun** [kercylan98/minotaur#69]
请教下在新版任务里，如果想实现类似于mmorpg里的任务线的配置怎么实现比较优雅

**Comment by kercylan98** [comment]
任务线应该以结合配置文件为主，程序仅需实现接取特定类型任务即可，配置参考：
![image](https://github.com/kercylan98/minotaur/assets/61743331/c62ad186-eba6-4e30-9f29-742f3693fc01)

**Comment by mozhiyun** [comment]
了解了，谢谢
